# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18fc58982ffe9ee4e2a10c23276c7ab0b911a1f41d30adb470b50ee7dea11f28fb722b5f1dc2ec35c8b14387ac8b3781b38c394357f4ca61d6110848c67f1705

test:
  secret_key_base: 4d708fd5f7c4606ed6232d2192254a32793de58797aee4e1b363cabd4ab1ffa2d77802f0d7c772f6f3961ea26e4d13e5675816bd67b5b8deac7b1309a30b2558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
